import type { Metadata } from 'next';
import { Sora } from 'next/font/google'
import './globals.css';

const sora = Sora({ 
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Landing Page Barber',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body className={sora.className}>{children}</body>
    </html>
  );
}
